version 1
Myshkina-Alla/team-project pull request #10
Opened 2023-07-02 15:30 UTC by werewolf2323

2023-07-03 14:53 UTC, Vovi1 requested changes
Добрий день Влад є питання по адаптиві він не працює  на точкових переломах крім desctop.

2023-07-03 18:17 UTC, wordisstuff requested changes
Я залишив коменти де що. Будуть питання пиши «гена»

2023-07-03 18:17 UTC, wordisstuff commented on src/css/vegetables.css
>    margin-left: 583px;
Такі марджени ніколи не ставлять. Подрібно по іншому позиціонувати

2023-07-03 18:17 UTC, wordisstuff commented on src/partials/vegetables.html
>          <use href="../images/icons.svg#Vector"></use>
В адресі зайва крапка в початку

2023-07-04 16:08 UTC, igorlyakh requested changes
Не работает планшетная версия

2023-07-04 18:58 UTC, merged