add html and css
Myshkina-Alla/team-project pull request #13
Opened 2023-07-02 22:19 UTC by Anna-Yavorska

2023-07-03 14:46 UTC, Vovi1 requested changes
Добрий день Анна є зауваження , що у вас є скрол , у формі колір самого тексту зробити на більш читабельним і приховати цифри , щоб зникали при воді .

2023-07-04 14:04 UTC, Myshkina-Alla approved these changes

2023-07-04 14:04 UTC, Myshkina-Alla approved these changes

2023-07-04 14:04 UTC, Vovi1 approved these changes

2023-07-04 14:04 UTC, merged