Hero
Myshkina-Alla/team-project pull request #15
Opened 2023-07-03 19:23 UTC by igorlyakh

2023-07-03 23:59 UTC, wordisstuff approved these changes

2023-07-04 08:13 UTC, Vovi1 requested changes
Wegetables  не застосовується тінь і rgba .

2023-07-04 17:04 UTC, Myshkina-Alla approved these changes

2023-07-04 17:05 UTC, Vovi1 approved these changes

2023-07-04 17:05 UTC, merged